import { ImobileProduct } from "../modules/mobile.interface";

export let mobileProducts : Array<ImobileProduct> = [
    {
      id: 1,
      name: 'iPhone 13',
      brand: 'Apple',
      price: 52000,
      image: 'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
      isAvailable: true,
      rating : 4.9,
      specification : ['128 GB ROM','15.49 cm (6.1 inch) Super Retina XDR Display',
      '12MP + 12MP | 12MP Front Camera','A15 Bionic Chip Processor'],
      deliveryCost : 10000,
      Qty : 'In Stock',
      offer : 'Save extra with Combo Offer'
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      brand: 'Samsung',
      price: 30000,
      image: '',
      isAvailable: false,
      rating : 4.5,
      specification : ['8 GB RAM | 128 GB ROM','16.26 cm (6.4 inch) Full HD+ Display',
      '12MP + 12MP + 8MP (OIS) | 32MP Front Camera','4500 mAh Lithium-ion Battery',
    'Snapdragon 888 Processor'],
    deliveryCost : 500,
    Qty : 'Out of Stock',
    offer : 'Bank Offer'
    },
    {
      id: 3,
      name: 'Google Pixel 6',
      brand: 'Google',
      price: 44000,
      image: 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
      isAvailable: false,
      rating : 3.9,
      specification : ['6 GB RAM | 128 GB ROM',
        '15.6 cm (6.14 inch) Full HD+ Display',
        '12.2MP + 12MP | 8MP Front Camera',
        '4410 mAh Battery',
        'Google Tensor Processor'],
        deliveryCost : 500,
        Qty : 'Out of Stock',
        offer : 'Save extra with Combo Offer'
    },
    {
      id: 4,
      name: 'OnePlus 9 Pro',
      brand: 'OnePlus',
      price: 47000,
      image: '',
      isAvailable: true,
      rating : 2.9,
      specification : ['12 GB RAM | 256 GB ROM',
        '17.02 cm (6.7 inch) Display',
        '48MP Rear Camera',
        '4500 mAh Battery'],
        deliveryCost : 1000,
        Qty : 'In Stock',
       offer : 'Bank Offer'

    },
    {
      id: 5,
      name: 'Xiaomi Mi 11',
      brand: 'Xiaomi',
      price: 16999,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating : 4.8,
      specification : ['8 GB RAM | 128 GB ROM | Expandable Upto 512 GB',
        '16.64 cm (6.55 inch) Full HD+ Display',
        '64MP + 8MP + 5MP | 16MP Front Camera',
        '4250 mAh Li-Polymer Battery',
        'Qualcomm Snapdragon 732G Processor'],
        deliveryCost : 150,
        Qty : 'In Stock',
        offer : 'Save extra with Combo Offer'
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III',
      brand: 'Sony',
      price: 19990,
      image: '',
      isAvailable: true,
      rating : 2.5,
      specification : ['1 GB RAM | 8 GB ROM | Expandable Upto 32 GB',
        '13.97 cm (5.5 inch) HD Display',
        '8MP Rear Camera | 5MP Front Camera',
        '2500 mAh Battery',
        'Qualcomm MSM8926 Processor'],
        deliveryCost : 200,
        Qty : 'In Stock',
      offer : 'Bank Offer'

    },
    {
      id: 7,
      name: 'LG Velvet',
      brand: 'LG',
      price: 50000,
      image: '',
      isAvailable: false,
      rating : 1.5,
      specification : ['Air-bubble Proof, Anti Fingerprint, Anti Glare, UV Protection, Washable Mobile',
        'Edge To Edge Tempered Glass',
        'Removable'],
        deliveryCost : 'Free Delivery',
        Qty : 'Out Stock',
        offer : 'Save extra with Combo Offer'
    },
    {
      id: 8,
      name: 'Huawei P40 Pro',
      brand: 'Huawei',
      price: 20000,
      image: '',
      isAvailable: true,
      rating : 3.5,
      specification : ['Anti Glare, Anti Fingerprint, Air-bubble Proof,Anti Reflection, Anti Reflection, Anti Bacterial Mobile',
       'Tempered Glass',
        'Removable'],
        deliveryCost : 'Free Delivery',
        Qty : 'In Stock',
       offer : 'Bank Offer'

    },
    {
      id: 9,
      name: 'Motorola Moto G Power',
      brand: 'Motorola',
      price: 25000,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating : 4.5,
      specification : ['4 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
        '16.76 cm (6.6 inch) HD+ Display',
        '50MP + 2MP | 16MP Front Camera',
        '6000 mAh Battery',
        'Helio G85 Processor',],
        deliveryCost : 'Free Delivery',
        Qty : 'In Stock',
        offer : 'Save extra with Combo Offer'

    },
    {
      id: 10,
      name: 'Nokia 8.3',
      brand: 'Nokia',
      price: 16999,
      image: '',
      isAvailable: true,
      rating : 4.5,
      specification : ['8 GB RAM | 256 GB ROM',
        '16.66 cm (6.56 inch) Display',
        '50MP Rear Camera',
        '5000 mAh Battery'],
        deliveryCost : 'Free Delivery',
        Qty : 'In Stock',
        offer : 'Bank Offer'

    }
  
  ];